### ISSUE TITLE
초기에 내려받으면 main(default) 브랜치에 소스파일이 존재하지 않습니다.

### ISSUE THREAD

**Issue by os-ym-baek** [ONE-store/onestore_iap_release#2]
아래의 명령어로 terminal 에서 소스를 내려받을 경우, README.md 밖에 없는 현상. 

```bash
git clone https://github.com/ONE-store/onestore_iap_release.git
```

소스가 있는 브랜치 iap19-release 이 아닌, main 이 default 로 되어 있는것이 원인으로 추정 됩니다.
대상 branch 에 대한 내용이 document 에 없어서 혼동을 줄 수 있을듯 합니다.

**Comment by powerji2001** [comment]
default branch를 v19로 변경하였습니다.. 추후 개선 버전 진행 시 master를 통해 안내하도록 하겠습니다.
피드백 감사합니다.
