### ISSUE TITLE
Error:Payment requested by abnormal app,code=12

### ISSUE THREAD

**Issue by LuoMaoqiang** [ONE-store/onestore_iap_release#4]
I got an error message when i launched the "sample_luckyone" demo,why?

**Comment by powerji2001** [comment]
Error Code 12 is RESULT_SECURITY_ERROR.
This error occurs when didn't upload apk.
If you want to develop using the SDK, your onestore account register test account in the our dev site.
If you wanto to real test, your test apk register in the dev site.
