### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by taehoonkeumdenny** [ONE-store/onestore_iap_release#5]
PurchaseClient 에 startConnection 후에 endConnection()을 하였으나, context를 계속해서 잡고 있는 것으로 보입니다.
이 때문에 Activity 가 종료되더라도 해당 context 가 앱 메모리에 계속해서 잡혀있는 상태가 됩니다.
서비스로 수행되는 App의 경우 해당 Activity를 계속 진입하고 종료를 반복하면 메모리가 누적됩니다.
<img width="718" alt="스크린샷 2023-01-19 오후 2 27 58" src="https://user-images.githubusercontent.com/64956998/213362658-e2595d11-5269-4f0f-a1ad-b78973a9184c.png">

v19 및 21.00.01 동일하게 발생합니다.

**Comment by powerji2001** [comment]
해당 내용 확인했습니다. 21.00.02에 해당 내용 수정하도록 하겠습니다. 
수정 사항의 배포 일정은 다시 알려드리겠습니다.
감사합니다.

**Comment by taehoonkeumdenny** [comment]
> 해당 내용 확인했습니다. 21.00.02에 해당 내용 수정하도록 하겠습니다. 수정 사항의 배포 일정은 다시 알려드리겠습니다. 감사합니다.

리포팅한지 한달 정도 되었는데, 배포 일정이 어떻게 되나요?

**Comment by powerji2001** [comment]
@taehoonkeumdenny 님, 내부적으로 수정은 완료를 하였으나, 검증 일정이 확보가 되지 않아서 배포가 지연되고 있습니다.
자세한 일정은 검증일정이 잡히는대로 메일로 공유 드리겠습니다.

**Comment by taehoonkeumdenny** [comment]
> @taehoonkeumdenny 님, 내부적으로 수정은 완료를 하였으나, 검증 일정이 확보가 되지 않아서 배포가 지연되고 있습니다. 자세한 일정은 검증일정이 잡히는대로 메일로 공유 드리겠습니다.

넵 답변 감사드립니다.

**Comment by powerji2001** [comment]
@taehoonkeumdenny 21.00.02 배포 완료하였습니다. 확인 부탁드립니다.
